//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Sao.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SaoEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SaoEntities object using the connection string found in the 'SaoEntities' section of the application configuration file.
        /// </summary>
        public SaoEntities() : base("name=SaoEntities", "SaoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaoEntities object.
        /// </summary>
        public SaoEntities(string connectionString) : base(connectionString, "SaoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SaoEntities object.
        /// </summary>
        public SaoEntities(EntityConnection connection) : base(connection, "SaoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Alumnos> Alumnos
        {
            get
            {
                if ((_Alumnos == null))
                {
                    _Alumnos = base.CreateObjectSet<Alumnos>("Alumnos");
                }
                return _Alumnos;
            }
        }
        private ObjectSet<Alumnos> _Alumnos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Cursos> Cursos
        {
            get
            {
                if ((_Cursos == null))
                {
                    _Cursos = base.CreateObjectSet<Cursos>("Cursos");
                }
                return _Cursos;
            }
        }
        private ObjectSet<Cursos> _Cursos;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Alumnos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAlumnos(Alumnos alumnos)
        {
            base.AddObject("Alumnos", alumnos);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cursos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCursos(Cursos cursos)
        {
            base.AddObject("Cursos", cursos);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaoModel", Name="Alumnos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Alumnos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Alumnos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Alumnos CreateAlumnos(global::System.Int32 id)
        {
            Alumnos alumnos = new Alumnos();
            alumnos.Id = id;
            return alumnos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DNI
        {
            get
            {
                return _DNI;
            }
            set
            {
                OnDNIChanging(value);
                ReportPropertyChanging("DNI");
                _DNI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DNI");
                OnDNIChanged();
            }
        }
        private global::System.String _DNI;
        partial void OnDNIChanging(global::System.String value);
        partial void OnDNIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Clave
        {
            get
            {
                return _Clave;
            }
            set
            {
                OnClaveChanging(value);
                ReportPropertyChanging("Clave");
                _Clave = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Clave");
                OnClaveChanged();
            }
        }
        private global::System.String _Clave;
        partial void OnClaveChanging(global::System.String value);
        partial void OnClaveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FechaIngreso
        {
            get
            {
                return _FechaIngreso;
            }
            set
            {
                OnFechaIngresoChanging(value);
                ReportPropertyChanging("FechaIngreso");
                _FechaIngreso = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FechaIngreso");
                OnFechaIngresoChanged();
            }
        }
        private Nullable<global::System.DateTime> _FechaIngreso;
        partial void OnFechaIngresoChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaIngresoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SaoModel", Name="Cursos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cursos : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Cursos object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Cursos CreateCursos(global::System.Int32 id)
        {
            Cursos cursos = new Cursos();
            cursos.Id = id;
            return cursos;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion
    
    }

    #endregion
    
}
